"""Backward-compatibility (release-gating) tests for the research-plans -> planboard
rename. Dual-recognition of content markers, env vars, ownership/fence markers, and
the hosted-config location must keep already-initialized projects and existing state
working. A regression here silently disables an integrity gate or orphans state. Run:
    python3 -m unittest tests.test_rename_compat -v
"""
import os
import sys
import tempfile
import unittest
from pathlib import Path

SCRIPTS = (
    Path(__file__).resolve().parents[1]
    / "skills" / "managing-planboard" / "scripts"
)
sys.path.insert(0, str(SCRIPTS))
import signoff_gate  # noqa: E402
import models  # noqa: E402
import board  # noqa: E402

NEW_MASTER = "<!-- planboard:master-plan -->"
OLD_MASTER = "<!-- research-plans:master-plan -->"
NEW_START = "<!-- planboard:start -->"
OLD_START = "<!-- research-plans:start -->"


def _make_project(tmp, master_marker, claude_marker):
    root = Path(tmp)
    (root / "plans").mkdir(parents=True, exist_ok=True)
    root_mp = root / "plans" / "master-plan.md"
    root_mp.write_text(
        (master_marker + "\n# Master plan\n") if master_marker else "# Master plan\n",
        encoding="utf-8",
    )
    cm = root / "CLAUDE.md"
    cm.write_text(
        (claude_marker + "\nconventions\n") if claude_marker else "conventions\n",
        encoding="utf-8",
    )
    return root


class FindProjectRootMarkers(unittest.TestCase):
    """find_project_root fails OPEN, so every old/new marker combination that a
    partially-migrated project can present must still be recognized."""

    def _probe(self, master_marker, claude_marker):
        with tempfile.TemporaryDirectory() as tmp:
            root = _make_project(tmp, master_marker, claude_marker)
            target = root / "plans" / "execution" / "01-x" / "v1.md"
            got = signoff_gate.find_project_root(target)
            return None if got is None else "root"

    def test_new_new(self):
        self.assertEqual(self._probe(NEW_MASTER, NEW_START), "root")

    def test_old_old(self):
        self.assertEqual(self._probe(OLD_MASTER, OLD_START), "root")

    def test_new_master_old_claude(self):
        self.assertEqual(self._probe(NEW_MASTER, OLD_START), "root")

    def test_old_master_new_claude(self):
        self.assertEqual(self._probe(OLD_MASTER, NEW_START), "root")

    def test_missing_master_marker_not_recognized(self):
        self.assertIsNone(self._probe(None, NEW_START))

    def test_missing_claude_marker_not_recognized(self):
        self.assertIsNone(self._probe(NEW_MASTER, None))


class EnvFallback(unittest.TestCase):
    VARS = (
        "PLANBOARD_NO_GATE", "RESEARCH_PLANS_NO_GATE",
        "PLANBOARD_GATE_TIMEOUT", "RESEARCH_PLANS_GATE_TIMEOUT",
    )

    def setUp(self):
        self._saved = {k: os.environ.get(k) for k in self.VARS}
        for k in self.VARS:
            os.environ.pop(k, None)

    def tearDown(self):
        for k, v in self._saved.items():
            if v is None:
                os.environ.pop(k, None)
            else:
                os.environ[k] = v

    def test_no_gate_new_only(self):
        os.environ["PLANBOARD_NO_GATE"] = "1"
        self.assertEqual(signoff_gate._env("NO_GATE"), "1")

    def test_no_gate_old_fallback(self):
        os.environ["RESEARCH_PLANS_NO_GATE"] = "1"
        self.assertEqual(signoff_gate._env("NO_GATE"), "1")

    def test_no_gate_new_wins(self):
        os.environ["PLANBOARD_NO_GATE"] = "1"
        os.environ["RESEARCH_PLANS_NO_GATE"] = "0"
        self.assertEqual(signoff_gate._env("NO_GATE"), "1")

    def test_timeout_new_valid_wins(self):
        os.environ["PLANBOARD_GATE_TIMEOUT"] = "300"
        os.environ["RESEARCH_PLANS_GATE_TIMEOUT"] = "900"
        self.assertEqual(signoff_gate.gate_timeout(), 300)

    def test_timeout_old_fallback(self):
        os.environ["RESEARCH_PLANS_GATE_TIMEOUT"] = "300"
        self.assertEqual(signoff_gate.gate_timeout(), 300)

    def test_timeout_malformed_new_falls_to_old(self):
        os.environ["PLANBOARD_GATE_TIMEOUT"] = "notanumber"
        os.environ["RESEARCH_PLANS_GATE_TIMEOUT"] = "300"
        self.assertEqual(signoff_gate.gate_timeout(), 300)

    def test_timeout_unset_default(self):
        self.assertEqual(signoff_gate.gate_timeout(), signoff_gate.DEFAULT_TIMEOUT)


class OwnershipMarker(unittest.TestCase):
    def _marker(self, brand):
        return "<!-- generated by %s /models · profile sha256:%s -->" % (brand, "a" * 64)

    def test_matches_both_brands_and_extracts_checksum(self):
        for brand in ("research-plans", "planboard"):
            m = models.MARKER_RE.search(self._marker(brand))
            self.assertIsNotNone(m, brand)
            self.assertEqual(m.group(1), "a" * 64)  # group(1) is the checksum, not the brand

    def test_unmarked_text_not_matched(self):
        self.assertIsNone(models.MARKER_RE.search("# just an agent\nno marker here\n"))


class ReportMarkerStrip(unittest.TestCase):
    def test_strips_both_prefixes(self):
        for pref in ("rp-report", "pb-report"):
            content = '<!-- %s {"schemaVersion": 1} -->\nBODY\n' % pref
            self.assertEqual(board._strip_report_marker(content), "BODY\n")

    def test_leaves_non_marker(self):
        self.assertEqual(board._strip_report_marker("# Title\nx"), "# Title\nx")


class HostedConfigFallback(unittest.TestCase):
    def _patched(self, new_dir, old_dir):
        board._web_data_dir = lambda: new_dir
        board._legacy_web_data_dir = lambda: old_dir

    def test_reads_legacy_when_new_absent(self):
        with tempfile.TemporaryDirectory() as newd, tempfile.TemporaryDirectory() as oldd:
            orig = (board._web_data_dir, board._legacy_web_data_dir)
            new_dir, old_dir = Path(newd) / "web", Path(oldd) / "web"
            self._patched(new_dir, old_dir)
            try:
                root = "/some/project"
                name = "%s.json" % board.web_project_hash(root)
                old_dir.mkdir(parents=True)
                (old_dir / name).write_text('{"url": "x", "pullKey": "k"}')
                self.assertEqual(board.read_web_config(root), {"url": "x", "pullKey": "k"})
            finally:
                board._web_data_dir, board._legacy_web_data_dir = orig

    def test_malformed_new_falls_to_old(self):
        with tempfile.TemporaryDirectory() as newd, tempfile.TemporaryDirectory() as oldd:
            orig = (board._web_data_dir, board._legacy_web_data_dir)
            new_dir, old_dir = Path(newd) / "web", Path(oldd) / "web"
            self._patched(new_dir, old_dir)
            try:
                root = "/some/project"
                name = "%s.json" % board.web_project_hash(root)
                new_dir.mkdir(parents=True)
                old_dir.mkdir(parents=True)
                (new_dir / name).write_text("not json")
                (old_dir / name).write_text('{"url": "old"}')
                self.assertEqual(board.read_web_config(root), {"url": "old"})
            finally:
                board._web_data_dir, board._legacy_web_data_dir = orig


class MigrateLegacyAgents(unittest.TestCase):
    MARKER = "<!-- generated by research-plans /models · profile sha256:%s -->" % ("b" * 64)

    def _agent(self, name):
        return (
            "---\n"
            "name: %s\n"
            "description: Review. Dispatched by /planboard:review.\n"
            "model: opus\n"
            "effort: max\n"
            "tools: Read\n"
            "---\n"
            "%s\n\nBody: run /planboard:review.\n" % (name, self.MARKER)
        )

    def _agents_dir(self, tmp):
        adir = Path(tmp) / ".claude" / "agents"
        adir.mkdir(parents=True)
        return adir

    def test_migrates_marked_agent_preserving_pins(self):
        with tempfile.TemporaryDirectory() as tmp:
            adir = self._agents_dir(tmp)
            (adir / "rp-plan-reviewer.md").write_text(self._agent("rp-plan-reviewer"))
            self.assertEqual(models.migrate_legacy_agents(Path(tmp)), ["pb-plan-reviewer"])
            self.assertFalse((adir / "rp-plan-reviewer.md").exists())
            new = (adir / "pb-plan-reviewer.md").read_text()
            self.assertIn("name: pb-plan-reviewer", new)
            self.assertIn("generated by planboard /models", new)
            self.assertNotIn("research-plans", new)
            self.assertIn("model: opus", new)  # pin preserved
            self.assertIn("effort: max", new)  # pin preserved
            self.assertIn("/planboard:review", new)

    def test_refuses_user_owned(self):
        with tempfile.TemporaryDirectory() as tmp:
            adir = self._agents_dir(tmp)
            (adir / "rp-plan-reviewer.md").write_text(
                "---\nname: rp-plan-reviewer\nmodel: sonnet\n---\nmy own agent\n"
            )
            self.assertEqual(models.migrate_legacy_agents(Path(tmp)), [])
            self.assertTrue((adir / "rp-plan-reviewer.md").exists())  # untouched
            self.assertFalse((adir / "pb-plan-reviewer.md").exists())

    def test_no_clobber_when_new_exists(self):
        with tempfile.TemporaryDirectory() as tmp:
            adir = self._agents_dir(tmp)
            (adir / "rp-plan-reviewer.md").write_text(self._agent("rp-plan-reviewer"))
            (adir / "pb-plan-reviewer.md").write_text(self._agent("pb-plan-reviewer"))
            self.assertEqual(models.migrate_legacy_agents(Path(tmp)), [])
            self.assertTrue((adir / "rp-plan-reviewer.md").exists())  # left alone


class LauncherMigration(unittest.TestCase):
    def test_removes_legacy_managed_launcher(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            legacy = root / board.LEGACY_LAUNCHER_NAME
            legacy.write_text("#!/bin/sh\n# %s\nexec :\n" % board.LEGACY_LAUNCHER_MARKER)
            board.ensure_launcher(root)
            self.assertTrue((root / board.LAUNCHER_NAME).exists())  # pb-board written
            self.assertFalse(legacy.exists())  # rp-board removed — no duplicate

    def test_keeps_foreign_legacy_launcher(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            legacy = root / board.LEGACY_LAUNCHER_NAME
            legacy.write_text("my own script\n")  # no ownership marker
            board.ensure_launcher(root)
            self.assertTrue(legacy.exists())  # user file untouched
            self.assertEqual(legacy.read_text(), "my own script\n")


if __name__ == "__main__":
    unittest.main()
