// Mirrors the payload board.py injects into the #board-data slot (schemaVersion 1).

export interface BoardData {
  schemaVersion: number;
  generatedAt: string;
  mode: "live" | "static" | "remote";
  focus: string | null;
  focusResults?: number | null; // --focus slug:rN opens the Results view on rN
  drift?: {
    // filesystem/git hygiene flags (feature #7); researcher modes only
    staleBoardHtml: boolean | null;
    leftoverStaging: string[];
    sourceDrift: string[];
  };
  // agent plan review (v0.9): reviewer-produced comments injected via
  // board.py --seed-annotations; resolved to anchors in the browser on mount.
  seededAnnotations?: SeededAnnotation[];
  shareHash?: string; // remote mode: Python-computed, echoed back in feedback
  gate?: { component: string; proposedVersion: number }; // sign-off gate mode
  gateBatch?: GateBatchEntry[]; // batch sign-off wizard (one plan at a time)
  project: { name: string; root?: string };
  git: {
    available: boolean;
    branch?: string;
    head?: string;
    fileDates?: Record<string, { firstCommit?: string; lastCommit?: string }>;
  };
  files: {
    masterPlan: BoardFile;
    decisionLog: BoardFile;
    executionPlans: ExecutionPlanGroup[];
    reviews: BoardFile[];
    history?: BoardFile; // reconstructed pre-adoption history; present only when it exists
  };
}

export interface BoardFile {
  path: string;
  content: string;
}

export interface GateBatchEntry {
  component: string;
  proposedVersion: number;
  path: string;
  content: string;
}

export interface ExecutionPlanGroup {
  component: string; // NN-slug
  versions: PlanVersionFile[];
  draft?: DraftFile;
  draftSnapshots?: DraftSnapshotFile[]; // committed within-version iterations (feature #1)
  results?: ResultsBundle[];
}

// ---- results bundles ----

export interface ResultsBundle {
  resultsVersion: number;
  dir: string;
  manifest: ResultsManifest | null;
  manifestRaw: BoardFile;
  report: BoardFile | null;
  verdict: ResultsVerdict | null;
  verdictRaw: BoardFile | null;
  scripts: BoardFile[];
  assets: Record<string, string>;
}

export interface ResultsManifest {
  schemaVersion: number;
  component: string;
  resultsVersion: number;
  planVersion: number | null;
  provenance: "planned" | "retrofit";
  trigger: "initial" | "redo-after-review" | "plan-revision";
  capturedAt: string;
  late?: boolean; // backfill: plan-governed work captured after the fact
  summary?: string;
  metrics: {
    label: string;
    value: string;
    note?: string;
    statement?: string; // finding-centric header: the claim sentence
    status?:
      | "robust"
      | "marginal"
      | "descriptive"
      | "retracted"
      | "superseded";
    artifactIds?: string[]; // artifact ids embedded under this finding
  }[];
  artifacts: ResultArtifact[];
}

export interface ResultArtifact {
  id: string;
  kind: "figure" | "table" | "other";
  title: string;
  caption?: string;
  file: string | null;
  data?: string | null;
  inlineText?: string;
  source: { path: string; sha256: string; bytes: number; oversized: boolean };
  producedBy: {
    script: string;
    sourcePath: string;
    lang?: string;
    // run recipe (additive, v0.6.3): present when the artifact can be
    // regenerated by re-running its producing code. See commands/results.md.
    command?: string[];
    cwd?: string;
    args?: string[];
    expectedOutputs?: string[];
    approvedHash?: string;
  } | null;
}

export interface ResultsVerdict {
  status: "accepted" | "changes-requested";
  date: string;
  planVersion: number | null;
  reviewer: string;
  comment?: string;
}

export interface VerdictRequest {
  component: string;
  resultsVersion: number;
  status: "accepted" | "changes-requested";
  comment: string;
}

export interface PlanVersionFile extends BoardFile {
  version: number;
}

export interface DraftFile extends BoardFile {
  proposedVersion: number;
}

// A committed within-version draft iteration (vN-draft-K.md). Immutable by
// convention (the sign-off gate does not guard these names); read-only on the
// board — viewed and diffed, never annotated.
export interface DraftSnapshotFile extends BoardFile {
  version: number;
  iteration: number;
}

// ---- parsed shapes (client-side contract parsing; see parse.ts) ----

export interface ParsedMasterPlan {
  ok: boolean;
  title: string;
  lastUpdated: string | null;
  contextMd: string; // Research questions subsection stripped out
  researchQuestions: ResearchQuestion[];
  components: TrackerRow[];
  sequencingMd: string | null;
  raw: string;
}

export interface ResearchQuestion {
  num: number;
  text: string;
}

export type TrackerStatus =
  | "not started"
  | "planned"
  | "in progress"
  | "done"
  | "done (verified)"
  | "dropped"
  | "unknown";

export interface TrackerRow {
  num: string;
  component: string;
  status: TrackerStatus;
  planLink: string;
  notes: string;
  serves: string; // raw Serves cell; "" for old 5-column tables
}

export interface ParsedLogEntry {
  timestamp: string;
  lateCaptured: boolean;
  fields: { label: string; text: string }[];
  raw: string;
}

export interface ParsedHistoryEntry {
  date: string; // YYYY-MM or YYYY-MM-DD (date-granularity; never a clock time)
  sortKey: string; // YYYY-MM-DD (month → first of month) for ordering
  title: string;
  fields: { label: string; text: string }[];
  raw: string;
}

export interface ParsedExecutionPlan {
  ok: boolean;
  title: string;
  version: number | null;
  componentSlug: string | null;
  date: string | null;
  provenance: string | null; // "Provenance:" header; null = prospective
  supersedes: string | null;
  goal: string | null; // "Goal and success criteria" body; null in pre-v0.3 plans
  serves: string | null; // "Serves:" line inside the goal section
  sections: { heading: string; content: string }[];
  signedOff: string | null;
  raw: string;
}

export interface Scorecard {
  schemaVersion: number;
  component: string;
  planVersion: number;
  planPath: string;
  rubricVersion: string;
  date: string;
  threshold?: ScorecardThreshold; // schemaVersion 2+
  items: ScorecardItem[];
  raw: number | null; // null on threshold fail/undetermined
  applicableMax: number | null;
  percent: number | null;
  band: string; // "not a plan" (fail) | "undetermined" | grade bands
  excluded?: { id: number | string; why: string }[];
  topRevisions?: string[];
  split?: { verdict: string; detail: string };
}

export interface ScorecardThreshold {
  verdict: "pass" | "undetermined" | "fail";
  checks: ThresholdCheck[];
  failures?: { id: string; verdict: string; fix?: string }[];
}

export interface ThresholdCheck {
  id: string;
  name?: string;
  result: "pass" | "fail" | "na" | "unknown";
  evidence?: string;
  note?: string;
}

export interface ScorecardItem {
  id: number | string; // 1..14 in v1, "G1".."G8" in v2
  name?: string;
  score: number | null;
  status?: string; // "N/A" | "unknown" when score is null
  evidence?: string;
  justification?: string;
}

// ---- annotations ----

export interface PlanCommentAnnotation {
  id: string;
  type: "plan-comment";
  planPath: string;
  component: string;
  version: number;
  isDraft: boolean;
  quote: string;
  prefix: string;
  suffix: string;
  sectionHeading: string;
  scope?: string; // always "" on plans (no stamps); optional for stored legacy comments
  occurrenceIndex: number;
  anchored: boolean;
  comment: string;
  author?: string; // reviewer agent that produced it (v0.9); absent = the researcher
}

// ---- agent plan review (v0.9) ----

// Rides the feedback fence: the button submits it, the session runs the agent.
export interface ReviewRequest {
  agent: "codex" | "gemini" | "subagent" | "panel";
  scope: "plan" | "master" | "results";
  component?: string;
  version?: number; // plan scope: the plan version
  resultsVersion?: number; // results scope: the bundle
  planPath?: string;
  isDraft?: boolean;
}

// A reviewer's comment before browser anchoring. board.py --seed-annotations
// injects a list of these; App turns each into a pending annotation keyed by
// `scope`: plan → PlanCommentAnnotation, master → DocCommentAnnotation (tracker),
// results → ResultCommentAnnotation (report target). Missing scope defaults to
// "plan" (the original Phase-1 shape).
export interface SeededAnnotation {
  scope?: "plan" | "master" | "results";
  // common to every scope
  sectionHeading: string;
  quote: string;
  comment: string;
  author: string;
  // plan scope
  planPath?: string;
  component?: string; // plan + results
  version?: number;
  isDraft?: boolean;
  // results scope
  resultsVersion?: number;
}

export interface DocCommentAnnotation {
  id: string;
  type: "doc-comment";
  view: "tracker" | "timeline" | "reviews";
  docKey: string; // "tracker" | "timeline" | review file payload path
  scope: string; // data-annot-scope id, "" when selection was outside stamps
  quote: string;
  prefix: string;
  suffix: string;
  sectionHeading: string;
  occurrenceIndex: number;
  anchored: boolean;
  comment: string;
  author?: string; // reviewer agent that produced it (v0.9); absent = the researcher
}

export interface GeneralAnnotation {
  id: string;
  type: "general";
  view: string;
  comment: string;
}

export interface ResultCommentAnnotation {
  id: string;
  type: "result-comment";
  component: string;
  resultsVersion: number;
  target: {
    kind: "artifact" | "report" | "metric";
    artifactId?: string;
    metricLabel?: string;
    quote?: string;
    occurrenceIndex?: number;
  };
  comment: string;
  author?: string; // reviewer agent that produced it (v0.9); absent = the researcher
  // Seeded reviewer comments (v0.9) start false and flip true when their report
  // quote paints; undefined on researcher-selected comments (always anchored).
  anchored?: boolean;
}

export interface ScriptCommentAnnotation {
  id: string;
  type: "script-comment";
  component: string;
  resultsVersion: number;
  script: string; // payload path of the snapshot
  lineStart: number;
  lineEnd: number;
  excerpt: string;
  comment: string;
}

export type Annotation =
  | PlanCommentAnnotation
  | GeneralAnnotation
  | ResultCommentAnnotation
  | ScriptCommentAnnotation
  | DocCommentAnnotation;
