#!/usr/bin/env python3
"""research-plans model profile — parse plans/model-profile.md and generate
project review agents in .claude/agents/. Stdlib only.

Subcommands:
    stage <key>   print one stage's row as JSON (empty output = no profile or
                  no usable row; parse warnings go to stderr)
    generate      write rp-*.md agent files from the profile (ownership-marked,
                  checksum-stamped; refuses same-named files without the marker)
    check         print a one-line hint when generated agents are stale
                  against the current profile
"""
import argparse
import hashlib
import json
import re
import sys
from pathlib import Path

STAGE_LABELS = {
    "plan": "plan",
    "execute": "execute",
    "sync": "sync",
    "plan review": "plan-review",
    "results validation": "results-validation",
    "board reviewer panel": "board-reviewer",
}
MODEL_ALIASES = {"inherit", "opus", "sonnet", "haiku", "fable"}
MODEL_ID_RE = re.compile(r"^claude-[a-z0-9.-]+$")
EFFORT_LEVELS = {"low", "medium", "high", "xhigh", "max"}
NO_EFFORT = {"", "-", "—", "–"}  # blank, hyphen, em dash, en dash
MECHANISMS = {"nudge", "agent"}
AGENT_STAGES = {
    "plan-review": "rp-plan-reviewer",
    "results-validation": "rp-results-validator",
    "board-reviewer": "rp-board-reviewer",
}
MARKER_RE = re.compile(
    r"<!-- generated by research-plans /models · profile sha256:([0-9a-f]{64}) -->"
)
MISMATCH_HINT = (
    "model profile changed since agents were generated — run /research-plans:models"
)
PROFILE_REL = Path("plans") / "model-profile.md"


def find_root(start=None):
    p = Path(start if start else Path.cwd()).resolve()
    for cand in (p, *p.parents):
        if (cand / "plans" / "master-plan.md").exists():
            return cand
    return p


def _norm(cell):
    return re.sub(r"\s+", " ", re.sub(r"\([^)]*\)", "", cell).strip().lower())


def _row_cells(line):
    s = line.strip()
    if not s.startswith("|"):
        return None
    return [c.strip() for c in s.strip("|").split("|")]


def _add_row(stages, warnings, cells, rownum):
    if len(cells) != 4:
        warnings.append(
            f"model-profile: skipping row {rownum} (expected 4 cells, got {len(cells)})"
        )
        return
    raw_stage, raw_model, raw_effort, raw_mech = cells
    key = STAGE_LABELS.get(_norm(raw_stage))
    if key is None:
        warnings.append(f"model-profile: skipping row {rownum} (unknown stage {raw_stage!r})")
        return
    if key in stages:
        warnings.append(f"model-profile: skipping row {rownum} (duplicate stage {raw_stage!r})")
        return
    model = raw_model.strip().lower()
    if model not in MODEL_ALIASES and not MODEL_ID_RE.match(model):
        warnings.append(f"model-profile: skipping row {rownum} (unknown model {raw_model!r})")
        return
    effort = raw_effort.strip().lower()
    if effort in NO_EFFORT:
        effort = None
    elif effort not in EFFORT_LEVELS:
        warnings.append(f"model-profile: skipping row {rownum} (unknown effort {raw_effort!r})")
        return
    mech = raw_mech.strip().lower()
    if mech not in MECHANISMS:
        warnings.append(
            f"model-profile: skipping row {rownum} (unknown mechanism {raw_mech!r})"
        )
        return
    stages[key] = {"stage": key, "model": model, "effort": effort, "mechanism": mech}


def parse_profile(text):
    """Return (stages, warnings). Strict: malformed rows are warned and skipped."""
    stages, warnings = {}, []
    lines = text.splitlines()
    i = 0
    while i < len(lines):
        cells = _row_cells(lines[i])
        if cells is not None and [_norm(c) for c in cells] == ["stage", "model", "effort", "mechanism"]:
            i += 1
            if i < len(lines):
                sep = _row_cells(lines[i])
                if sep is not None and set("".join(sep)) <= set("-: "):
                    i += 1
            rownum = 0
            while i < len(lines):
                cells = _row_cells(lines[i])
                if cells is None:
                    break
                rownum += 1
                _add_row(stages, warnings, cells, rownum)
                i += 1
            break
        i += 1
    if not stages and not warnings:
        warnings.append("model-profile: no stage/model/effort/mechanism table found")
    return stages, warnings


def load_profile(root):
    """Return (stages, warnings, exists)."""
    path = root / PROFILE_REL
    if not path.exists():
        return {}, [], False
    stages, warnings = parse_profile(path.read_text(encoding="utf-8"))
    return stages, warnings, True


def cmd_stage(root, key):
    stages, warnings, exists = load_profile(root)
    if not exists:
        return 0
    for w in warnings:
        print(w, file=sys.stderr)
    row = stages.get(key)
    if row:
        print(json.dumps(row))
    return 0


def cmd_generate(root):  # implemented in a later task
    raise NotImplementedError


def cmd_check(root):  # implemented in a later task
    raise NotImplementedError


def main(argv=None):
    ap = argparse.ArgumentParser(description="research-plans model profile tools")
    ap.add_argument("--root", default=None, help="project root (default: walk up to plans/master-plan.md)")
    sub = ap.add_subparsers(dest="cmd", required=True)
    p_stage = sub.add_parser("stage", help="print one stage's profile row as JSON")
    p_stage.add_argument("key", choices=sorted(set(STAGE_LABELS.values())))
    sub.add_parser("generate", help="write rp-*.md agents from the profile")
    sub.add_parser("check", help="hint when generated agents are stale")
    args = ap.parse_args(argv)
    root = Path(args.root).resolve() if args.root else find_root()
    if args.cmd == "stage":
        return cmd_stage(root, args.key)
    if args.cmd == "generate":
        return cmd_generate(root)
    return cmd_check(root)


if __name__ == "__main__":
    sys.exit(main())
